language: node_js
node_js:
  - "10.16.3"

sudo: true
dist: xenial

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

branches:
  only:
    - master

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - npm install

script:
  - ng e2e
