language: node_js
node_js:
  - "10.16.3"

sudo: true
dist: bionic

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

install:
  - npm install

script:
  - chrome --version
  - google-chrome --version
  - ng e2e
