language: node_js
node_js:
  - "10.16.3"

sudo: true
dist: xenial

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

services:
  - xvfb

branches:
  only:
    - master

install:
  - npm install

script:
  - xvfb-run --server-args="-screen 0 1024x768x24" ng e2e
